### PR TITLE
Add an option: Automatically update TOC when I open a `.md` file

### LINKED ISSUE #3: Add an option: Automatically update TOC when I open a `.md` file
Cf. https://github.com/nok/markdown-toc/issues/83

### PR DESCRIPTION
**Pull request by wyster**
codemill-id-57cb07a25681420300fc7c6b fixes #3

### CODE REVIEW

**Comment by lanceplaine** [comment]
Hi @wyster, do you want to apply the clean method @ssamuli is talking about https://github.com/lanceplaine/markdown-toc/pull/4#issuecomment-244622552 before we merge the PR?

**Comment by wyster** [comment]
This method is called only when you open the editor, i did that it was updated by direct editing, he also called when the file is opened

**Comment by lanceplaine** [comment]
Sorry maybe my question wasn't clear enough.

Do you think your code is clean enough (with the `setTimeout`) so @nok will accept to merge it into the [original repository](https://github.com/nok/markdown-toc)?

**Comment by wyster** [comment]
I dont see problem, but there is another variant, update list after document saved or opened, see branch https://github.com/wyster/markdown-toc/tree/feature/updateTocAfterSave
commit - https://github.com/wyster/markdown-toc/commit/1969f9895db51efddd97737fe9ff20617e328048

**Comment by lanceplaine** [comment]
I will merge the PR. Hopefully it will be good to merge in the original repo.

**Comment by lanceplaine** [comment]
Tested, looks good to me

**Comment by lanceplaine** [comment]
@wyster Just so you know: https://gitter.im/CodeMillApp/support :)

**Comment by wyster** [comment]
@lanceplaine thanks, i received payment for this task ;)

**Pull request merged**
